import React, { useCallback, useEffect, useState } from "react";
import {
  Alert,
  AlertActionCloseButton,
  Badge,
  Spinner,
  Tab,
  Tabs,
  TabTitleText,
} from "@patternfly/react-core";
import { api } from "./api.js";
import DiscoveryView from "./DiscoveryView.jsx";
import ClassifyView from "./ClassifyView.jsx";
import ReviewView from "./ReviewView.jsx";

const POLL_MS = 5000;
const ROLE_ORDER = { "control-plane": 0, "infra": 1, "worker": 2, "storage": 3 };

export default function App() {
  const [nodes, setNodes] = useState([]);
  const [loading, setLoading] = useState(true);
  const [fetchError, setFetchError] = useState(null);
  const [activeTab, setActiveTab] = useState("discovery");
  const [selections, setSelections] = useState({});
  const [alert, setAlert] = useState(null);

  const fetchNodes = useCallback(async () => {
    try {
      const data = await api.listNodes();
      const fetched = data.nodes || [];
      setNodes(fetched);
      setSelections(prev => {
        const merged = { ...prev };
        for (const node of fetched) {
          if (node.role && !merged[node.id]) {
            merged[node.id] = {
              role: node.role,
              hostname: node.hostname || "",
              interface_selected: node.interface_selected || "",
              disk_selected: node.disk_selected || "",
            };
          }
        }
        return merged;
      });
      setFetchError(null);
    } catch (err) {
      setFetchError(err.message);
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => { fetchNodes(); }, [fetchNodes]);

  useEffect(() => {
    if (activeTab !== "discovery") return;
    const id = setInterval(fetchNodes, POLL_MS);
    return () => clearInterval(id);
  }, [activeTab, fetchNodes]);

  const handleSelect = (nodeId, field, value) => {
    setSelections(prev => ({
      ...prev,
      [nodeId]: { ...(prev[nodeId] || {}), [field]: value },
    }));
  };

  const handleClassify = useCallback(async () => {
    const payload = Object.entries(selections)
      .map(([id, fields]) => ({ id, ...fields }))
      .filter(n => n.role && n.hostname);
    if (payload.length === 0) {
      setAlert({ variant: "warning", title: "Assign at least one node with a role and hostname." });
      return;
    }
    try {
      await api.classifyNodes(payload);
      await fetchNodes();
      setAlert({ variant: "success", title: `${payload.length} node(s) classified successfully.` });
      setActiveTab("review");
    } catch (err) {
      setAlert({ variant: "danger", title: "Classification failed.", body: err.message });
    }
  }, [selections, fetchNodes]);

  const handleReset = useCallback(async () => {
    if (!window.confirm("Reset all classifications? All role, hostname, and NIC/disk selections will be cleared.")) return;
    try {
      await api.resetNodes();
      setSelections({});
      await fetchNodes();
      setAlert({ variant: "info", title: "All classifications reset." });
      setActiveTab("classify");
    } catch (err) {
      setAlert({ variant: "danger", title: "Reset failed.", body: err.message });
    }
  }, [fetchNodes]);

  const handleExport = useCallback(async () => {
    const classified = nodes
      .filter(n => n.role)
      .slice()
      .sort((a, b) => {
        const ra = ROLE_ORDER[a.role] ?? 99;
        const rb = ROLE_ORDER[b.role] ?? 99;
        if (ra !== rb) return ra - rb;
        return (a.hostname || "").localeCompare(b.hostname || "");
      });
    if (classified.length === 0) {
      setAlert({ variant: "warning", title: "No classified nodes to export." });
      return;
    }
    try {
      await api.generate({ nodes: classified.map(n => ({ id: n.id })) });
      const lines = [
        "# cluster-vars.yaml — generated by dcm-site-ui",
        "# Usage: ansible-playbook install_abi.yml -e @cluster-vars.yaml -e @secrets.yaml",
        "",
        "ocp_nodes:",
      ];
      for (const node of classified) {
        lines.push(`  - hostname: ${node.hostname}`);
        lines.push(`    role: ${node.role}`);
        lines.push(`    ip: ${node.ip}`);
        lines.push(`    serial: ${node.serial}`);
        if (node.interface_selected) lines.push(`    interface_selected: ${node.interface_selected}`);
        if (node.disk_selected) lines.push(`    disk_selected: "${node.disk_selected}"`);
      }
      const blob = new Blob([lines.join("\n") + "\n"], { type: "text/yaml" });
      const url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = "cluster-vars.yaml";
      a.click();
      URL.revokeObjectURL(url);
    } catch (err) {
      setAlert({ variant: "danger", title: "Export failed.", body: err.message });
    }
  }, [nodes]);

  const classifiedCount = nodes.filter(n => n.role).length;
  const pendingCount = nodes.filter(n => !n.role).length;

  return (
    <div>
      <div style={{
        background: "#151515",
        color: "#fff",
        padding: "0.75rem 1.5rem",
        display: "flex",
        alignItems: "center",
        gap: "1rem",
      }}>
        <span style={{ fontWeight: 600, fontSize: "1.1rem" }}>dcm-site-ui</span>
        <span style={{ color: "#8a8d90", fontSize: "0.875rem" }}>
          OCP cluster discovery and classification — Phase 3
        </span>
      </div>

      <div style={{ padding: "1.5rem" }}>
        {fetchError && (
          <Alert
            variant="danger"
            title="Backend unreachable"
            actionClose={<AlertActionCloseButton onClose={() => setFetchError(null)} />}
            style={{ marginBottom: "1rem" }}
          >
            {fetchError}
          </Alert>
        )}
        {alert && (
          <Alert
            variant={alert.variant}
            title={alert.title}
            actionClose={<AlertActionCloseButton onClose={() => setAlert(null)} />}
            style={{ marginBottom: "1rem" }}
          >
            {alert.body}
          </Alert>
        )}

        <Tabs
          activeKey={activeTab}
          onSelect={(_, key) => setActiveTab(key)}
          style={{ marginBottom: "1.5rem" }}
        >
          <Tab
            eventKey="discovery"
            title={
              <TabTitleText>
                Discovery <Badge isRead style={{ marginLeft: "0.25rem" }}>{nodes.length}</Badge>
              </TabTitleText>
            }
          >
            {loading
              ? <div style={{ textAlign: "center", padding: "3rem" }}><Spinner /></div>
              : <DiscoveryView nodes={nodes} onNavigate={() => setActiveTab("classify")} />
            }
          </Tab>

          <Tab
            eventKey="classify"
            title={
              <TabTitleText>
                Classify <Badge isRead style={{ marginLeft: "0.25rem" }}>{pendingCount} pending</Badge>
              </TabTitleText>
            }
          >
            <ClassifyView
              nodes={nodes}
              selections={selections}
              onSelect={handleSelect}
              onClassify={handleClassify}
              onReset={handleReset}
            />
          </Tab>

          <Tab
            eventKey="review"
            title={
              <TabTitleText>
                Review + Export <Badge isRead style={{ marginLeft: "0.25rem" }}>{classifiedCount} ready</Badge>
              </TabTitleText>
            }
          >
            <ReviewView nodes={nodes} onExport={handleExport} onReset={handleReset} />
          </Tab>
        </Tabs>
      </div>
    </div>
  );
}
